FROM alpine

ARG MESASDKVERSION=22.6.1

RUN wget --no-verbose -U "" -O /mesasdk.tar.gz http://www.astro.wisc.edu/~townsend/resource/download/mesasdk/mesasdk-x86_64-linux-${MESASDKVERSION}.tar.gz &&\
    tar -xvf /mesasdk.tar.gz \
