version: '2'
services:
  mesa-sdk:
    build:
      context: mesa-sdk
    image: ghcr.io/hombit/mesa-sdk:22.6.1
  mesa2py:
    build:
      context: .
      args:
        - PYTHON_VERSION=3.10
    image: ghcr.io/hombit/mesa2py:r22.05-python3.10
    depends_on:
      - mesa-sdk
