name: CI

on: [push, pull_request]

jobs:
  docker-mesa2py:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build container
        run: docker build -t mesa2py .
